### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by jaideep11061982** [SinicaGroup/Class-agnostic-Few-shot-Object-Counting#2]
@littlepenguin89106 @Brian96086 @Hacker-Davinci 
Is it possible to get the trained model which can be finetuned for other datasets ?

**Comment by Future-Outlier** [comment]
Unfortunately, we don't have it.
We can only promise you that his model is a correct reimplementation of CFOCNet.
But we strongly recommend you use pretrained resnet50  instead of non-pretrained resnet50 to train the model.
It will make you converge faster.

**Comment by jaideep11061982** [comment]
@Hacker-Davinci  what about this i see [model.ckpt](https://github.com/SinicaGroup/Class-agnostic-Few-shot-Object-Counting/blob/main/ckpt/model.ckpt)
